language: android
jdk: oraclejdk8
sudo: required
dist: precise
env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
android:
  components:
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
licenses:
  - android-sdk-license-.+
  - google-gdk-license-.+
script:
  - ./gradlew test --stacktrace --no-daemon
before_install:
  - chmod +x gradlew
branches:
  only:
    - develop